/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Comments: typeof import('./src/components/Comments.vue')['default']
    CommentsItem: typeof import('./src/components/CommentsItem.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderSearch: typeof import('./src/components/HeaderSearch.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoItem: typeof import('./src/components/VideoItem.vue')['default']
  }
}
